name: Pull Request Tests

on:
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: temurin

permissions:
  contents: read

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title follows Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: maven

      - name: Run tests
        run: mvn clean test -B

      - name: Build project
        run: mvn compile -B